### ISSUE TITLE
Internationalisation of the plugin

### ISSUE THREAD

**Issue by mattab** [surenjie/VisitorAvatar#1]
Hi there,

It's great to see your plugin on the Piwik Marketplace, congratulations :+1: 

I have a little suggestion here, maybe you could make the plugin international in Chinese and English? we wrote a little guide for this on the blog: http://piwik.org/blog/2014/10/how-to-make-your-plugin-multilingual-introducing-the-piwik-platform/

Cheers,
Matt
Piwik founder

**Comment by surenjie** [comment]
Thanks for your advice, I try next:)
