### ISSUE TITLE
不兼容最新版的 piwik

### ISSUE THREAD

**Issue by vvianyy** [surenjie/VisitorAvatar#3]

**Comment by surenjie** [comment]
请问是不能安装，还是报错，或是没效果？

**Comment by vvianyy** [comment]
是没效果哈，如下图，头像并没有出现，而是显示为 URL。如果是这样的话还不如不加这个自定义字段呢，本来是想直观一点用来辨认谁是谁的。

![854c4313-fdef-44c0-a763-8a4dc4c64c94](https://cloud.githubusercontent.com/assets/2127129/11712973/739d5af2-9f6b-11e5-9c05-eb86aad9bcf8.JPG)

2015-12-09 0:48 GMT+08:00 renjie notifications@github.com:

**Comment by vvianyy** [comment]
@surenjie 补了一张出错的图，请看看，或者加我详聊怎么改，我自己改也行

**Comment by surenjie** [comment]
@bokeyy ，我本地建了一个Piwik最新2.15.0版本环境使用正常

根据你截图那也不算出错（删除插件也这样，是原生功能），其实是自定义变量的使用问题

首先头像不是在列表页上直接展示的，而是在右上角查看访客资料的详情浮层里展示
其次根据你截图得知你的自定义变量名称为portraitUrl，对应值则直接在前端就上报包括协议的完整URI
那可猜测出访客头像链接规则的配置就只有%s？

其实访客头像链接规则的配置是想让前端自定义变量的单纯，比如id、email、username等，而不是一个完整大部分硬编码的绝对地址
所以我理解你这里只要上报ed281004，然后头像链接规则配置//himg.baidu.com/sys/portraitn/item/%s
但由于ed281004不像是一个直观值，大可继续使用其它自定义变量来构造你认为直观的信息，最终都会在列表页面一起展示的（原生功能）

但是很遗憾目前的功能只能在详情页面展示规则头像，这是因为piwik本来规划设计就有接口，所以可以简单继承实现，未来如果有时间可以考虑尝试列表页面也提供相应的头像功能

**Comment by vvianyy** [comment]
额，可是你说的这种上报方式似乎不行，因为我不知道究竟有几种 URL

在 2015年12月10日 下午9:13，renjie notifications@github.com写道：
